import { describe, expect, it } from 'vitest';
import { ProjectError } from '../../src/project/errors.js';
import { isYarnBerry, parseYarnLockfile } from '../../src/project/lockfile/yarn.js';

const FILE = 'yarn.lock';

const classic = `# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1


"@angular/core@~10.2.0", "@angular/core@^10.0.0":
  version "10.2.5"
  resolved "https://registry.yarnpkg.com/@angular/core/-/core-10.2.5.tgz#2050b0dbb180aa98c2ec46bba6d4827565ba2a2d"
  integrity sha512-AAAA
  dependencies:
    tslib "^2.0.0"

"@ngrx/store@^10.0.0":
  version "10.1.2"
  resolved "https://registry.yarnpkg.com/@ngrx/store/-/store-10.1.2.tgz"

"rxjs@>=6.5.3 <7":
  version "6.6.7"

"toastr-alias@npm:ngx-toastr@^13.0.0":
  version "13.2.1"

tslib@^2.0.0:
  version "2.0.3"
`;

const berry = `# This file is generated by running "yarn install" inside your project.
# Manual changes might be lost - proceed with caution!

__metadata:
  version: 6
  cacheKey: 8

"@angular/core@npm:~15.2.0, @angular/core@npm:^15.0.0":
  version: 15.2.10
  resolution: "@angular/core@npm:15.2.10"
  dependencies:
    tslib: ^2.3.0
  peerDependencies:
    rxjs: ^6.5.3 || ^7.4.0
    zone.js: ~0.11.4 || ~0.12.0 || ~0.13.0
  checksum: abc
  languageName: node
  linkType: hard

"my-app@workspace:.":
  version: 0.0.0-use.local
  resolution: "my-app@workspace:."
  dependencies:
    "@angular/core": ~15.2.0
    rxjs: ~7.8.0
    shared: "workspace:*"
    toastr-alias: "npm:ngx-toastr@^16.0.0"
    typescript: ~4.9.4
  languageName: unknown
  linkType: soft

"rxjs@npm:~7.8.0":
  version: 7.8.1
  resolution: "rxjs@npm:7.8.1"
  languageName: node
  linkType: hard

"shared@workspace:*, shared@workspace:packages/shared":
  version: 0.0.0-use.local
  resolution: "shared@workspace:packages/shared"
  languageName: unknown
  linkType: soft

"toastr-alias@npm:ngx-toastr@^16.0.0":
  version: 16.2.0
  resolution: "ngx-toastr@npm:16.2.0"
  languageName: node
  linkType: hard

"typescript@npm:~4.9.4":
  version: 4.9.5
  resolution: "typescript@npm:4.9.5"
  languageName: node
  linkType: hard

"typescript@patch:typescript@~4.9.4#~builtin<compat/typescript>":
  version: 4.9.5
  resolution: "typescript@patch:typescript@npm%3A4.9.5#~builtin<compat/typescript>::version=4.9.5&hash=23ec76"
  languageName: node
  linkType: hard
`;

describe('parseYarnLockfile (Yarn 1 classic)', () => {
  it('resolves entries by the exact package.json descriptor, including combined keys', () => {
    expect(isYarnBerry(classic)).toBe(false);
    const lock = parseYarnLockfile(classic, FILE);
    expect(lock.kind).toBe('yarn-classic');
    expect(lock.formatVersion).toBe('1');
    expect(lock.resolve('@angular/core', '~10.2.0')).toBe('10.2.5');
    expect(lock.resolve('@ngrx/store', '^10.0.0')).toBe('10.1.2');
    expect(lock.resolve('rxjs', '>=6.5.3 <7')).toBe('6.6.7');
    expect(lock.resolve('toastr-alias', 'npm:ngx-toastr@^13.0.0')).toBe('13.2.1');
    // A range that is not in the lockfile (package.json edited after install) is not guessed.
    expect(lock.resolve('@ngrx/store', '^11.0.0')).toBeUndefined();
    expect(lock.resolve('constructor', '^1.0.0')).toBeUndefined();
  });

  it('accepts merge conflicts Yarn can resolve on its own', () => {
    const merged = `# yarn lockfile v1

<<<<<<< HEAD
rxjs@^6.5.0:
  version "6.5.5"
=======
rxjs@^6.5.0:
  version "6.6.7"
>>>>>>> feature
`;
    const lock = parseYarnLockfile(merged, FILE);
    expect(lock.resolve('rxjs', '^6.5.0')).toMatch(/^6\.\d+\.\d+$/);
  });

  it('parses a file that ends in a comment without a newline', () => {
    const started = performance.now();
    const lock = parseYarnLockfile('# yarn lockfile v1\n\nrxjs@^6.5.0:\n  version "6.6.7"\n# end', FILE);
    expect(lock.resolve('rxjs', '^6.5.0')).toBe('6.6.7');
    expect(performance.now() - started).toBeLessThan(1000);
  });

  it.each([
    ['an unterminated string', 'foo@^1.0.0:\n  version "1.0.0\n  bad: [\n'],
    ['an unterminated string at the end', '# yarn lockfile v1\n\nfoo@^1.0.0:\n  version "1.0.0'],
    ['a stray token', '# yarn lockfile v1\n\n{ broken\n'],
    ['bad indentation', 'foo@^1.0.0:\n   version "1.0.0"\n'],
    ['a newer lockfile version', '# yarn lockfile v99\n\nfoo@^1.0.0:\n  version "1.0.0"\n'],
  ])('rejects %s quickly with a typed error', (_label, text) => {
    const started = performance.now();
    let caught: unknown;
    try {
      parseYarnLockfile(text, FILE);
    } catch (error) {
      caught = error;
    }
    expect(caught).toBeInstanceOf(ProjectError);
    expect((caught as ProjectError).code).toBe('MALFORMED_LOCKFILE');
    expect((caught as ProjectError).message).not.toMatch(/\n/);
    expect(performance.now() - started).toBeLessThan(1000);
  });
});

describe('parseYarnLockfile (Yarn 2+ berry)', () => {
  it('resolves entries through the root workspace descriptors', () => {
    expect(isYarnBerry(berry)).toBe(true);
    const lock = parseYarnLockfile(berry, FILE);
    expect(lock.kind).toBe('yarn-berry');
    expect(lock.formatVersion).toBe('6');
    expect(lock.resolve('@angular/core', '~15.2.0')).toBe('15.2.10');
    expect(lock.resolve('rxjs', '~7.8.0')).toBe('7.8.1');
    expect(lock.resolve('typescript', '~4.9.4')).toBe('4.9.5');
    expect(lock.resolve('toastr-alias', 'npm:ngx-toastr@^16.0.0')).toBe('16.2.0');
    expect(lock.resolve('shared', 'workspace:*')).toBeUndefined();
    expect(lock.resolve('missing', '^1.0.0')).toBeUndefined();
  });

  it('falls back to the package.json range when there is no workspace entry', () => {
    const text = `__metadata:
  version: 8
  cacheKey: 10c0

"@angular/core@npm:^19.0.0":
  version: 19.2.14
  resolution: "@angular/core@npm:19.2.14"
  languageName: node
  linkType: hard
`;
    const lock = parseYarnLockfile(text, FILE);
    expect(lock.formatVersion).toBe('8');
    expect(lock.resolve('@angular/core', '^19.0.0')).toBe('19.2.14');
  });

  it('ignores __proto__ keys and inherited properties', () => {
    const text = `__metadata:
  version: 8

"my-app@workspace:.":
  version: 0.0.0-use.local
  resolution: "my-app@workspace:."
  dependencies:
    __proto__: "npm:^1.0.0"
  linkType: soft
`;
    const lock = parseYarnLockfile(text, FILE);
    expect(lock.resolve('constructor', '^1.0.0')).toBeUndefined();
    expect(({} as Record<string, unknown>).version).toBeUndefined();
  });

  it.each([
    ['invalid YAML', '__metadata:\n  version: 6\n"a@npm:^1.0.0":\n  version: [1\n'],
    ['an entry that is not a map', '__metadata:\n  version: 6\n"a@npm:^1.0.0": 3\n'],
    ['metadata without a version', '__metadata:\n  cacheKey: 8\n'],
  ])('rejects %s with a typed error', (_label, text) => {
    let caught: unknown;
    try {
      parseYarnLockfile(text, FILE);
    } catch (error) {
      caught = error;
    }
    expect(caught).toBeInstanceOf(ProjectError);
    expect((caught as ProjectError).code).toBe('MALFORMED_LOCKFILE');
    expect((caught as ProjectError).message).not.toMatch(/\n/);
  });
});
